import type { KanbanTicket } from "@/components/kanban-board"

export const dashboardMockTickets: KanbanTicket[] = [
  {
    id: "TK-1234",
    title: "Email sync not working on mobile devices after iOS update",
    priority: 2,
    status: "in-progress",
    category: "Email",
    assignee: { name: "Sarah Chen", initials: "SC" },
    createdAt: "2h ago",
    tags: ["iOS", "Mobile"],
  },
  {
    id: "TK-1242",
    title: "Email sync not working on mobile devices after iOS update",
    priority: 2,
    status: "in-progress",
    category: "Email",
    assignee: { name: "Sarah Chen", initials: "SC" },
    createdAt: "1h ago",
    tags: ["Android", "Mobile"],
  },
  {
    id: "TK-1235",
    title: "Request for new 27-inch monitor for design team",
    priority: 4,
    status: "open",
    category: "Hardware",
    createdAt: "4h ago",
    tags: ["Equipment"],
  },
  {
    id: "TK-1236",
    title: "VPN disconnects frequently when switching networks",
    priority: 3,
    status: "open",
    category: "Network",
    createdAt: "6h ago",
    tags: ["VPN", "Critical"],
  },
  {
    id: "TK-1237",
    title: "Software license renewal for Adobe Creative Suite",
    priority: 3,
    status: "in-progress",
    category: "Software",
    assignee: { name: "Emily Davis", initials: "ED" },
    createdAt: "1d ago",
    tags: ["License"],
  },
  {
    id: "TK-1238",
    title: "Printer not connecting to network after office move",
    priority: 2,
    status: "open",
    category: "Hardware",
    createdAt: "1d ago",
    tags: ["Printer", "Network"],
  },
  {
    id: "TK-1239",
    title: "Password reset request for legacy system access",
    priority: 5,
    status: "resolved",
    category: "Access",
    assignee: { name: "John Doe", initials: "JD" },
    createdAt: "2d ago",
    tags: ["Password"],
  },
  {
    id: "TK-1240",
    title: "Laptop running slow - possible malware infection",
    priority: 1,
    status: "in-progress",
    category: "Security",
    assignee: { name: "Alex Wong", initials: "AW" },
    createdAt: "3h ago",
    tags: ["Urgent", "Security"],
  },
  {
    id: "TK-1241",
    title: "Zoom video quality issues during meetings",
    priority: 4,
    status: "resolved",
    category: "Software",
    assignee: { name: "Sarah Chen", initials: "SC" },
    createdAt: "3d ago",
    tags: ["Video", "Conference"],
  },
]

export const ticketCategories = ["All", "Email", "Hardware", "Network", "Software", "Security", "Access"]
export const ticketPriorities = ["All", "P1", "P2", "P3", "P4", "P5"]
